### ISSUE TITLE
[REQUEST] Support for .zs files

### ISSUE THREAD

**Issue by evil-trainer** [NX-Editor/NxEditor#58]
Hi!

So, I've been trying to create a fan translation for the upcoming Mario game "Mario vs Donkey Kong" and I'm using the demo to start training this skill (I'm a total noob in Switch fan translations). I succesfully extracted all the files with the game's texts and I was told Nx Editor could edit the filetype is used for text rendering in the game. Well, turns out I tried Nx Editor and I got a "IHandle filetype not supported" error. So, I'd like to request support for this filetype (.zs) so we all can work with it on Nx Editor, if possible!

**Comment by evil-trainer** [comment]
> .zs is not the extension of the file, it just means that it is a ZSTD compressed file Usually Nintendo places the extension just before, so for example like *.sarc.zs

Oh, I see. So, is it possible to implement a way to support this format?

**Comment by MasterBubbles** [comment]
It depends the actual format of the file, .zs isn't the actual file's extension.
It's like if you took a .png file, compressed it in a .zip archive and named it .png.zip
You'd need to know what is the actual file's extension
What is the full name of the file?

**Comment by evil-trainer** [comment]
USen.Product.dmo.sarc.zs

> It depends the actual format of the file, .zs isn't the actual file's extension. It's like if you took a .png file, compressed it in a .zip archive and named it .png.zip You'd need to know what is the actual file's extension What is the full name of the file?

USen.Product.dmo.sarc.zs

**Comment by MasterBubbles** [comment]
> USen.Product.dmo.sarc.zs

Interesting, does the game dump for Mario vs Donkey Kong include a file called `Pack/ZsDic.pack.zs` or something similar that contain "zsdic" in the name (or in the file extension)?

If so, then it can be ZSTD decompressed using those as dictionaries, if not then it can probably be decompressed without dictionaries.

SARC files, once you've done the ZSTD decompressing, are editable either with Switch Toolbox or with NX Editor

**Comment by evil-trainer** [comment]
> > USen.Product.dmo.sarc.zs
> 
> Interesting, does the game dump for Mario vs Donkey Kong include a file called `Pack/ZsDic.pack.zs` or something similar that contain "zsdic" in the name (or in the file extension)?
> 
> If so, then it can be ZSTD decompressed using those as dictionaries, if not then it can probably be decompressed without dictionaries.
> 
> SARC files, once you've done the ZSTD decompressing, are editable either with Switch Toolbox or with NX Editor

It does contain the `Pack/` folder, but not the `ZsDic.pack.zs` file
![Captura de tela 2024-02-07 155959](https://github.com/NX-Editor/NxEditor/assets/149848175/101eccf2-fabd-41d4-81b1-fc06ea520503)
![Captura de tela 2024-02-07 160016](https://github.com/NX-Editor/NxEditor/assets/149848175/0ae4ebdc-6124-4f55-8228-ab01aa356757)
![Captura de tela 2024-02-07 160039](https://github.com/NX-Editor/NxEditor/assets/149848175/652516e9-1cca-4510-80de-966ac4de8785)

**Comment by MasterBubbles** [comment]
In that case I recommend using Switch Toolbox, that tool is better suited, it supports both ZSTD compressed files and SARC archives. You should be able to directly open the file without needing to do the ZSTD decompressing
[https://github.com/KillzXGaming/Switch-Toolbox](https://github.com/KillzXGaming/Switch-Toolbox)

**Comment by evil-trainer** [comment]
> In that case I recommend using Switch Toolbox, that tool is better suited, it supports both ZSTD compressed files and SARC archives. You should be able to directly open the file without needing to do the ZSTD decompressing https://github.com/KillzXGaming/Switch-Toolbox

Ok, then! Thank you for your time anyway! 😁👍🏻

**Comment by MasterBubbles** [comment]
If needed, because it's .sarc archives contain multiple other files, you can extract them with Switch Toolbox and open those with other tools depending on the types of files you find inside those

**Comment by MasterBubbles** [comment]
Oh, by the way, is it a Mals file? By that I mean files contained in a "Mals" folder. If so, then it means the SARC archive contains MSBT files, which you can directly edit with [MSBT-Editor](https://gitlab.com/AeonSake/msbt-editor/-/releases) (basically the same as NX Editor but not dependent on the TOTK ZSTD dictionaries to function I think)

**Comment by ArchLeaders** [comment]
@evil-trainer NX-Editor supports SARC, ZS, and MSBT, you need to install the TotK and the EPD plugin.

**Comment by evil-trainer** [comment]
> Oh, by the way, is it a Mals file? By that I mean files contained in a "Mals" folder. If so, then it means the SARC archive contains MSBT files, which you can directly edit with [MSBT-Editor](https://gitlab.com/AeonSake/msbt-editor/-/releases) (basically the same as NX Editor but not dependent on the TOTK ZSTD dictionaries to function I think)

Oh, that might just do it for me then! Gotta try it now! Thanks!

**Comment by evil-trainer** [comment]
> @evil-trainer NX-Editor supports SARC, ZS, and MSBT, you need to install the TotK and the EPD plugin.

Wait, I thought I did that? When 1st running the installer there's a prompt for installing them, right? I'm pretty sure I did install that but it seems I didn't 😅

**Comment by MasterBubbles** [comment]
Well while Arch was answering, since the demo is free on the eshop I installed and dumped it to test. I can confirm that it works well with NX Editor when the TotK and EPD plugins are installed correctly

**Comment by ArchLeaders** [comment]
It might require a dummy ZsDic.pack.zs file to function, I didn't implement that part very gracefully.

**Comment by evil-trainer** [comment]
> It might require a dummy ZsDic.pack.zs file to function, I didn't implement that part very gracefully.

Well, guess my dumb request may be used to implement that :P
Hopefully I could help some way then lol
